### ISSUE TITLE
/atrdeny doesn't work properly

### ISSUE THREAD

**Issue by SeaOrangejuice** [morelaid/AcceptTheRules-Files#6] opened 2024-02-14 07:41 UTC
Server Version: Paper 1.20.4
![image](https://github.com/morelaid/AcceptTheRules-Files/assets/116551329/99bea44c-611d-4f1d-9c65-fb4488a6f259)
[Report.zip](https://github.com/morelaid/AcceptTheRules-Files/files/14276553/Report.zip)

**Comment by morelaid** [comment] 2024-02-14 19:23
![image](https://github.com/morelaid/AcceptTheRules-Files/assets/37469978/978e166b-1f41-4503-af6e-b8257d747cbf)
Please use the support channels I offer. This is not one of my supported support options and makes the process on my side unnecessarily complex. In addition, messages can be unintentionally overlooked here.

Unfortunately, your case cannot be reproduced with the current Paper version and ATR version, as you can see from my image. Please check the permissions so that you can test the plugin without OP permissions.

Note: Do not necessarily post the report file openly (that's why I offer other ways, because it contains your Lastest.log file).

I will close this and you can use one of my supported ways, if you need more help.

**Closed as completed by morelaid** 2024-02-14 19:23 UTC
